version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: video-transcoder-docker
    ports:
      - 5080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    links:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.7
    ports:
      - 6672:5672
      - 16672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: RiyasFBD849
